# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaGLAM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstaGLAM
  pod 'Appirater'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'FirebaseFirestoreSwift'
  


  target 'InstaGLAMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstaGLAMUITests' do
    # Pods for testing
  end

end
